#!/bin/bash
echo "-----------------------------------------------------------------------"
echo "Create sym links"
ln -sf /usr-share/primtux-password-ctparental-change/primtux-password-ctparental-change.py /usr/bin/primtux-password-ctparental-change
echo "Symbolic links created."
ls -l /usr/bin/perte-mot-de-passe-ctparental
echo "-----------------------------------------------------------------------"
exit 0
